// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abwowueybxankcnkqcar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFid293dWV5YnhhbmtjbmtxY2FyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkxODM5MzgsImV4cCI6MjA1NDc1OTkzOH0.mUY3dnoHZavjJqW2jLDWCV3rpdHOE9VVigzXvgaCAWo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);